<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.test</groupId>
    <artifactId>event-ledger-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>Event Ledger</name>
    <description>Aggregator for Event Gateway and Account Service microservices</description>

    <modules>
        <module>account-service</module>
        <module>event-gateway</module>
    </modules>
</project>
