package com.test.accountservice;

import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import com.test.accountservice.model.Account;
import com.test.accountservice.model.Transaction;
import com.test.accountservice.model.TransactionType;
import com.test.accountservice.repository.AccountRepository;
import com.test.accountservice.repository.TransactionRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Pact Provider test — verifies the Account Service satisfies
 * the contract defined by the Event Gateway (consumer).
 *
 * Reads pact from: ../event-gateway/target/pacts/
 * (generated by EventGatewayContractTest during the gateway build)
 *
 * The provider states seed the database with the data each
 * interaction expects to find.
 */
@Provider("account-service")
@PactFolder("../event-gateway/target/pacts")
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class AccountServiceContractTest {

    @LocalServerPort
    int port;

    @Autowired
    private AccountRepository accountRepository;

    @Autowired
    private TransactionRepository transactionRepository;

    @BeforeEach
    void setupTarget(PactVerificationContext context) {
        context.setTarget(new HttpTestTarget("localhost", port));
    }

    // ── Provider state handlers ───────────────────────────────────

    @State("account acct-pact-001 may or may not exist")
    void accountMayNotExist() {
        // No setup needed — the Account Service auto-creates
        // accounts on the first transaction (see AccountManager).
    }

    @State("account acct-pact-002 exists with balance")
    void accountExistsWithBalance() {
        // Seed the account + a CREDIT transaction so getBalance works
        if (accountRepository.findById("acct-pact-002").isEmpty()) {
            accountRepository.save(Account.builder()
                    .accountId("acct-pact-002")
                    .currency("USD")
                    .build());

            transactionRepository.save(Transaction.builder()
                    .transactionId("txn-seed-002")
                    .accountId("acct-pact-002")
                    .type(TransactionType.CREDIT)
                    .amount(BigDecimal.valueOf(1000.00))
                    .currency("USD")
                    .eventTimestamp(Instant.parse("2026-01-01T00:00:00Z"))
                    .build());
        }
    }

    // ── Pact verification engine ──────────────────────────────────

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void pactVerificationTestTemplate(PactVerificationContext context) {
        context.verifyInteraction();
    }
}
